server:
    port: 8989
spring:
  application:
    name: service-miya
  zipkin:
      base-url: http://localhost:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/,http://eureka-server-2:8762/eureka/,http://eureka-server-3:8763/eureka/